apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-api
  namespace: expense-tracker
  labels:
    app: expense-tracker-api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: expense-tracker-api
