-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hashedPassword" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "provider" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "providerId" TEXT;
